apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-quiz
  template:
    metadata:
      labels:
        app: game-quiz
    spec:
      containers:
        - name: game-quiz
          image: ghcr.io/casperh17/quiz-game:latest
          imagePullPolicy: Always