apiVersion: apps/v1
kind: Deployment
metadata:
  name: vejr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vejr
  template:
    metadata:
      labels:
        app: vejr
    spec:
      containers:
        - name: vejr
          image: ghcr.io/casperh17/vejr:latest
          imagePullPolicy: Always