name: Byg docker image

on:
    push: 
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Byg docker image
              run: docker build -t "hello-python" ./helloworlddocker
